#!/usr/bin/env bash
#A Bash script that installs nginx web server.
# It should be listening to port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
