#!/usr/bin/env bash
# Configuring Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > sudo /var/www/html/index.nginx-debian
sed -i "301 Moved Permanently" /redirect_me
