#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend \
web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver \
78806-web-01 54.158.182.245:80 check\n\tserver 78806-web-02 54.146.93.24:80 \
check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
