#!/usr/bin/env bash
# A Bash script that pings an IP address passed as an argument
# Requirements:
#	It aacepts a string bas an argument
#	It displays "Usage:5-is_the_host_on_the_network {IP_ADDRESS}" if there is no argument passed
#	Pings the IP 5 times
if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
