#!/usr/bin/env bash
# A short and sweet bash script to configure a server
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill "$(pgrep 'nginx' | head -1)"
