#!/usr/bin/env bash
# A Bash script that stops "4-to_infinity_and_beyond" process
# Requirements:
#	You must use "kill"
pid=$(pgrep "bash ./ infinity and beyond" -f)
if [ -n "$pid" ];
then
	kill "$pid"
fi
