#!/usr/bin/env bash
# A Bash script displaying numbers from 1 to 100:
#	Displays FizzBuzz when number is a multiple of 3 and 5
#	Displays Fizz when number is a multiple of 3
#	Displays Buzz when number is a multiple of 5
#	Otherwise, displayss the number
#	In a list format

for number in {1..100};
do
	if ((number % 3 == 0 && number % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((number % 3 == 0))
	then
		echo "Fizz"
	elif ((number % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$number"
	fi
done
