#!/usr/bin/env bash
# A Bash script looping from 1 t0 10 displaying:
#	'bad luck' for the 4th iteration
#	'good luck' for the 8th iteration
#	'Best School' for the other iterations

num_of_times=0
while [ $num_of_times -lt 10 ];
do
	if [ $num_of_times -eq 3 ];
	then
		echo "bad luck"
	elif [ $num_of_times -eq 7 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( num_of_times++ ))
done
