#!/usr/bin/env bash
# A Bash script displaying:
#	The content of the current directory,
#	In a list format.
#	And where only the part of the name after the first dash is displayed

LIST=$(ls -1)
for list in $LIST;
do
	echo "$list" | cut -d '-' -f2
done
