#!/usr/bin/env bash
# Install the ufw and set up few rules on web-01
sudo apt-get ufw
sudo ufw disable
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
