#!/usr/bin/env bash
# nginx must run as nginx user
# nginx must be listening on all active IPs on port 8080

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
